- name: BBuddy
  hosts: all
  become: Yes
  vars:
    tomcat_version: 8.5.14
    install_dir: /opt
    cache_dir: /vagrant
    java_version_map:
      "8u131": jdk1.8.0_131
    java_version_checksum:
      "8u131": "sha512:5f5428ad9a0bcd20533cafc7c28bd260064da2f00719c3b5dc4a970771ffae11b1b9a18bfef39476c448d63d3efb829641a6c22ffb8faa3bbb7b5b3670487d80"
  roles:
    - role: mysql
      mysql:
        user: nerd
        pass: dbs3cr3t
        name: bbuddydev
    - role: jdk
      jdk_version: 8u131
    - role: gradle
      gradle_version: 2.13
  
  #tasks:

    # - name: 获取 Tomcat
    #   get_url: >
    #     url="https://d.chaifeng.com/mirror/apache-tomcat-{{ tomcat_version }}.tar.gz"
    #     dest="{{ cache_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"

    # - name: Catalina Home
    #   set_fact:
    #     catalina_home: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"

    # - name: 安装 Tomcat
    #   unarchive: >
    #     remote_src=True
    #     src="{{ cache_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    #     dest="{{ catalina_home | dirname }}"
    #     creates="{{ catalina_home }}/bin/startup.sh"

    # - name: 为 BBuddy 生成临时目录
    #   tempfile: state=directory
    #   register: bbuddy_dir

    # - name: 获取 BBuddy 代码
    #   git: >
    #     repo="https://github.com/nerds-odd-e/bbuddy.git"
    #     dest="{{ bbuddy_dir.path }}"
    #     clone=yes

    # - name: 构建 BBuddy
    #   shell: |
    #     source /etc/profile
    #     cd {{ bbuddy_dir.path }}
    #     gradle war
    #   args:
    #     executable: /bin/bash

    # - name: 关闭 Tomcat
    #   shell: |
    #     source /etc/profile
    #     export CATALINA_HOME="{{ catalina_home }}"

    #     if pgrep -lf "/bin/java .+${CATALINA_HOME}"; then
    #         "$CATALINA_HOME/bin/shutdown.sh"
    #     fi

    #     SHUTDOWN_TIMEOUT=30
    #     while pgrep -lf "/bin/java .+${CATALINA_HOME}" && [[ "$SHUTDOWN_TIMEOUT" -gt 0 ]]; do
    #         sleep 1
    #         : $(( SHUTDOWN_TIMEOUT-- ))
    #     done
    #     if [[ "$SHUTDOWN_TIMEOUT" -le 0 ]]; then
    #         pgrep -f "/bin/java .+${CATALINA_HOME}" | xargs kill -9
    #     fi
    #   args:
    #     executable: /bin/bash

    # - name: 删除 Tomcat 自带的根应用
    #   file: path="{{ item }}" state=absent
    #   with_items:
    #     - "{{ catalina_home }}/webapps/ROOT.war"
    #     - "{{ catalina_home }}/webapps/ROOT"

    # - name: 部署 BBuddy
    #   copy: remote_src=Yes src="{{ bbuddy_dir.path }}/build/libs/bbuddy-HEAD.war" dest="{{ catalina_home }}/webapps/ROOT.war"

    # - name: 启动 Tomcat
    #   shell: |
    #     source /etc/profile
    #     export CATALINA_HOME="{{ catalina_home }}"

    #     nohup "${CATALINA_HOME}/bin/startup.sh"
    #     sleep 25
    #   args:
    #     executable: /bin/bash
