spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbuddytest?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8090

cucumber:
  port: 8100
  context-path: /#/app
